from pathlib import Path
import os
import shutil
import subprocess
import requests
from dotenv import load_dotenv
import config
from services.local_db import setup_database
from models.load_ollama_model import start_ollama_server


def _read_env(path: Path) -> dict[str, str]:
    env_values: dict[str, str] = {}
    if not path.exists():
        return env_values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        env_values[key.strip()] = value.strip()
    return env_values


def _write_env(path: Path, env_values: dict[str, str]) -> None:
    header = [
        "# Jarvis environment configuration",
        "# Generated by `jarvis init`.",
        "# Use ';' to separate paths for list values on Windows.",
        "",
    ]

    ordered_keys = [
        "WEATHER_API_KEY",
        "JARVIS_CONFIG_DIR",
        "JARVIS_DATA_DIR",
        "JARVIS_ENV_PATH",
        "JARVIS_GPT_MODEL",
        "JARVIS_WHISPER_MODEL",
        "JARVIS_WAKE_WORD_MODEL_PATH",
        "JARVIS_WHISPER_MODEL_PATH",
        "JARVIS_MEMORY_DB_PATH",
        "JARVIS_LOCAL_DB_PATH",
    ]

    lines = header[:]
    for key in ordered_keys:
        if key in env_values:
            lines.append(f"{key}={env_values[key]}")

    for key in env_values:
        if key not in ordered_keys:
            lines.append(f"{key}={env_values[key]}")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def ensure_runtime_dirs() -> None:
    config.CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    config.DATA_DIR.mkdir(parents=True, exist_ok=True)
    Path(config.MEMORY_DB_PATH).mkdir(parents=True, exist_ok=True)
    Path(config.LOCAL_DB_PATH).parent.mkdir(parents=True, exist_ok=True)


def ensure_env_file(force_update: bool = False) -> Path:
    env_path = config.ENV_PATH
    current_values = _read_env(env_path)

    default_values = {
        "WEATHER_API_KEY": "",
        "JARVIS_CONFIG_DIR": str(config.CONFIG_DIR),
        "JARVIS_DATA_DIR": str(config.DATA_DIR),
        "JARVIS_ENV_PATH": str(env_path),
        "JARVIS_GPT_MODEL": config.GPT_MODEL,
        "JARVIS_WHISPER_MODEL": config.WHISPER_MODEL,
        "JARVIS_MEMORY_DB_PATH": str(Path(config.DATA_DIR) / "memory"),
        "JARVIS_LOCAL_DB_PATH": str(Path(config.DATA_DIR) / "local.db"),
    }

    for key, value in default_values.items():
        if key == "WEATHER_API_KEY" and current_values.get(key):
            continue
        if force_update or key not in current_values or current_values[key] == "":
            current_values[key] = value

    _write_env(env_path, current_values)
    load_dotenv(dotenv_path=env_path, override=True)
    return env_path


def _ensure_ollama_available() -> None:
    if shutil.which("ollama") is None:
        raise RuntimeError("Ollama is not installed or not available in PATH.")


def _pull_ollama_model(model_name: str) -> None:
    result = subprocess.run(
        ["ollama", "pull", model_name],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        details = (result.stderr or result.stdout or "Unknown ollama error").strip()
        raise RuntimeError(f"Failed to pull Ollama model '{model_name}': {details}")


def run_bootstrap(
    skip_model_download: bool = False,
    skip_ollama_pull: bool = False,
    force_update: bool = False,
) -> dict:
    ensure_runtime_dirs()
    env_path = ensure_env_file(force_update=force_update)
    summary: dict[str, object] = {"env_path": str(env_path)}

    if not skip_ollama_pull:
        _ensure_ollama_available()
        start_ollama_server()
        _pull_ollama_model(config.GPT_MODEL)
        summary["ollama_model"] = config.GPT_MODEL

    if not skip_model_download:
        from services.model_downloads import download_runtime_models

        downloaded_paths = download_runtime_models(
            whisper_model=config.WHISPER_MODEL,
            models_root=Path(config.DATA_DIR) / "models",
        )
        env_values = _read_env(env_path)
        env_values["JARVIS_WAKE_WORD_MODEL_PATH"] = downloaded_paths["wake_word_model_path"]
        env_values["JARVIS_WHISPER_MODEL_PATH"] = downloaded_paths["whisper_model_path"]
        _write_env(env_path, env_values)
        summary["downloaded_models"] = downloaded_paths

    setup_database()
    summary["database_path"] = str(Path(config.LOCAL_DB_PATH))
    summary["memory_db_path"] = str(Path(config.MEMORY_DB_PATH))
    return summary


def run_doctor() -> list[dict[str, str | bool]]:
    checks: list[dict[str, str | bool]] = []

    def add_check(name: str, ok: bool, detail: str) -> None:
        checks.append({"name": name, "ok": ok, "detail": detail})

    add_check("Config directory", config.CONFIG_DIR.exists(), str(config.CONFIG_DIR))
    add_check("Data directory", config.DATA_DIR.exists(), str(config.DATA_DIR))
    add_check("Env file", config.ENV_PATH.exists(), str(config.ENV_PATH))
    add_check("Ollama in PATH", shutil.which("ollama") is not None, "ollama")
    add_check("Wake model path", Path(config.WAKE_WORD_MODEL_PATH).exists(), config.WAKE_WORD_MODEL_PATH)
    add_check("Whisper model path", Path(config.WHISPER_MODEL_PATH).exists(), config.WHISPER_MODEL_PATH)
    add_check("Memory DB dir", Path(config.MEMORY_DB_PATH).exists(), config.MEMORY_DB_PATH)
    add_check("Local DB dir", Path(config.LOCAL_DB_PATH).parent.exists(), str(Path(config.LOCAL_DB_PATH).parent))

    weather_api_key = os.getenv("WEATHER_API_KEY", "")
    add_check("Weather API key", bool(weather_api_key.strip()), "WEATHER_API_KEY in .env")

    try:
        response = requests.get("http://localhost:11434/api/tags", timeout=1)
        add_check("Ollama server", response.status_code == 200, "http://localhost:11434/api/tags")
    except Exception:
        add_check("Ollama server", False, "http://localhost:11434/api/tags")

    return checks
